### ISSUE TITLE
Allow configuration of the screenshots folder location

### ISSUE THREAD

**Issue by timtyrrell** [vitorgalvao/screenshots-workflow#1]
### Feature details

I wasn't certain if there was a way to do this now?

**Comment by vitorgalvao** [comment]
It’s not currently possible, but you’re not the first to ask so I’ll consider it for the next version.

**Comment by tddschn** [comment]
No screenshots show up for me - where's the default location?

**Comment by vitorgalvao** [comment]
Try [this version](https://github.com/vitorgalvao/screenshots-workflow/files/15155222/Screenshots.alfredworkflow.zip) which allows setting a custom location. Note functionality may change before the release version.
