### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by spsisys** [vitorgalvao/screenshots-workflow#4]
### Feature details

Right now, the workflow doesn't find screenshots when folder set to OneDrive path (used with CleanShot X). Would be great help for users like me are using OneDrive to store and share screenshots. 10X!

**Comment by vitorgalvao** [comment]
See https://github.com/vitorgalvao/screenshots-workflow/issues/3. It applies to all cloud providers.

Any screenshot not found will be related to your local setup, not the workflow, which asks Spotlight for its data.

**Comment by vitorgalvao** [comment]
My mistake, I was erroneously[^1] ignoring stuff in Library. Update to 2024.5 and you should be good to go.

[^1]: It was done on purpose initially, but I forgot to remove that bit when I made the folder customisable.
